version = 3.42.5
[default]
[default.deploy]
[default.deploy.parameters]
s3_prefix = "serverless-ghost"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DomainName=\"\" EnableDebugLogs=\"true\" EnableNat=\"false\" UseServerlessDb=\"true\" SentryDsn=\"\" SesSmtpPassword=\"\""
